default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: Alcatraz@1982
  host: localhost

development:
  <<: *default
  database: recipe_app_development

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  database: recipe_app_production
